

/**
 * @author anzha2250
 */
public class FrmDiceGame extends javax.swing.JFrame {

    /**
     * Creates new form FrmDiceGame
     */
    public FrmDiceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDiceRoll = new javax.swing.JLabel();
        lblRollValue = new javax.swing.JLabel();
        lblRolls = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        lblUserGuess = new javax.swing.JLabel();
        btnRollDice = new javax.swing.JButton();
        txtUserGuess = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        lblHeader.setText("Super Dice Guessing Game");

        lblInst1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblInst1.setText("Enter Number From 1 to 6");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setText("And click Roll To Roll The Dice");

        lblDiceRoll.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblDiceRoll.setText("Dice Roll");

        lblRollValue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRollValue.setText("0");

        lblRolls.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblRolls.setText("Number of rolls:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Number of correct guesses:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Number of incorrect guesses:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("Percentage of correct guesses:");

        lblRollsValue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRollsValue.setText("0");

        lblCorrectValue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCorrectValue.setText("0");

        lblIncorrectValue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblIncorrectValue.setText("0");

        lblPercentValue.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPercentValue.setText("0");

        lblUserGuess.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblUserGuess.setText("You Guess ");

        btnRollDice.setText("Roll Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        txtUserGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserGuessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserGuess)
                            .addComponent(lblUserGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addComponent(btnRollDice)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiceRoll)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblRollValue))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeader)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(lblInst1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRolls, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRollsValue)
                    .addComponent(lblCorrectValue)
                    .addComponent(lblIncorrectValue)
                    .addComponent(lblPercentValue))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserGuess)
                    .addComponent(lblDiceRoll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRollDice)
                    .addComponent(lblRollValue))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRolls)
                    .addComponent(lblRollsValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCorrectValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblIncorrectValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblPercentValue))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserGuessActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        double totalRolls = 0;
        int totalCorrect = 0;
        int totalIncorrect = 0;
        int userGuess;
        int diceRoll;
        double percCorrect = 0;
        
        diceRoll = (int)Math.round(Math.random()*5+1);
        lblRollValue.setText(String.valueOf(diceRoll));
        
        userGuess = Integer.parseInt(txtUserGuess.getText());
        
        totalRolls = totalRolls + 1;
        
        if (diceRoll == userGuess)
        {
            totalCorrect = totalCorrect + 1;
        }
        else
        {
            totalIncorrect = totalIncorrect + 1;
        }
        
        percCorrect = ((double)totalCorrect/(double)totalRolls)*100;
        
        percCorrect = percCorrect * 100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect / 100;
        
        percCorrect = ((double)totalCorrect/(double)totalRolls)*100;
        
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percCorrect));
        
    }//GEN-LAST:event_btnRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblDiceRoll;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollValue;
    private javax.swing.JLabel lblRolls;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblUserGuess;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables

    private void setText(String valueOf) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
